proxy_location: EveryNode

applications:

- name: "default"
  route_prefix: "/"
  import_path: chaos_test.receiver:alpha
  runtime_env:
    working_dir: https://github.com/ray-project/serve_workloads/archive/8931755384dff5c9c721879b0e5f04525cf3665f.zip
  deployments:
  - name: Receiver
    num_replicas: 3
    ray_actor_options:
      num_cpus: 0
      resources:
        node_singleton: 1
