proxy_location: EveryNode

applications:

- name: "default"
  route_prefix: "/"
  import_path: spot_chaos_test.receiver:alpha
  runtime_env:
    working_dir: https://github.com/ray-project/serve_workloads/archive/47075f7a226d05ae62da73cdc6e19ef1d6e9984e.zip
  deployments:
  - name: Receiver
    num_replicas: 3
    ray_actor_options:
      num_cpus: 0
      resources:
        node_singleton: 1
