# Make sure to fill in your target_url and bearer_token. See README.

import_path: chaos_test.pinger:graph

runtime_env:
  working_dir: https://github.com/ray-project/serve_workloads/archive/2e2bb93b1d399c84f7a3142991c59a9ca6034f96.zip
  env_vars:
    RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S: '1'

host: 0.0.0.0

port: 8000

deployments:
- name: Pinger
  num_replicas: 1
  user_config:
    target_url: YOUR_RECEIVER_URL
    bearer_token: YOUR_RECEIVER_BEARER_TOKEN
    kill_interval: 1500
    default_on: 1
  ray_actor_options:
    num_cpus: 1