import_path: chaos_test.receiver:alpha

runtime_env:
  working_dir: https://github.com/ray-project/serve_workloads/archive/3dfa2118f355418dfbd5cfe8626d501ba42b9a67.zip
  env_vars:
    RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S: '1'

host: 0.0.0.0

port: 8000

deployments:
- name: Receiver
  num_replicas: 3
  ray_actor_options:
    num_cpus: 0
    resources:
      node_singleton: 1
- name: NodeKiller
  num_replicas: 1
  ray_actor_options:
    num_cpus: 0
    resources:
      node_singleton: 1
- name: DiskLeaker
  num_replicas: 1
  ray_actor_options:
    num_cpus: 0
    resources:
      leak_singleton: 1
