import_path: chaos_test.receiver:alpha

runtime_env:
  working_dir: https://github.com/ray-project/serve_workloads/archive/2907b755b7bb69253a7ff93d32a80fb829ac0dea.zip
  env_vars:
    RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S: '1'

host: 0.0.0.0

port: 8000

deployments:
- name: NodeKiller
  num_replicas: 1
  ray_actor_options:
    num_cpus: 0
- name: Receiver
  num_replicas: 3
  ray_actor_options:
    num_cpus: 0
    resources:
      node_singleton: 1
