proxy_location: EveryNode

applications:

- name: "default"
  route_prefix: "/"
  import_path: chaos_test.receiver:alpha
  runtime_env:
    working_dir: https://github.com/ray-project/serve_workloads/archive/8931755384dff5c9c721879b0e5f04525cf3665f.zip
    env_vars:
      RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S: '1'
      RAY_SERVE_ENABLE_EXPERIMENTAL_STREAMING: '1'
  deployments:
  - name: Receiver
    num_replicas: 3
    ray_actor_options:
      num_cpus: 0
      resources:
        alpha_singleton: 1
  - name: NodeKiller
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0
      resources:
        node_singleton: 1
  - name: DiskLeaker
    num_replicas: 1
    user_config:
      num_GB: 10
    ray_actor_options:
      num_cpus: 0
      resources:
        leak_singleton: 1
