import_path: chaos_test.receiver:graph

runtime_env:
  working_dir: https://github.com/ray-project/serve_workloads/archive/2e2bb93b1d399c84f7a3142991c59a9ca6034f96.zip
  env_vars:
    RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S: '1'

host: 0.0.0.0

port: 8000

deployments:
- name: NodeKiller
  num_replicas: 1
  ray_actor_options:
    num_cpus: 0
- name: Receiver
  num_replicas: 3
  ray_actor_options:
    num_cpus: 0
    resources:
      node_singleton: 1
