import_path: single_node_test.receiver:graph

runtime_env:
  working_dir: https://github.com/ray-project/serve_workloads/archive/4d2c104afc68ff854078b796c16082b9807a18d8.zip
  env_vars:
    RAY_SERVE_REQUEST_PROCESSING_TIMEOUT_S: '1'

host: 0.0.0.0

port: 8000

deployments:
- name: Receiver
  num_replicas: 1
  ray_actor_options:
    num_cpus: 0
    resources:
      node_singleton: 1
